[package]
name = "finance"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
askama = "0.16"
clap = { version = "4", features = ["derive"] }
csv = "1"
indexmap = { version = "2", features = ["serde"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
temporal_rs = "0.2"
